version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: on-failure
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: the-bedechka-case

  nginx:
    image: nginx:1.19.0-alpine
    build:
      context: .
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: on-failure
    volumes:
      - './app/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - './app/:/usr/src/app'
    restart: on-failure
    depends_on:
      - db
    environment:
      APP_ENV: dev
      APP_SECRET: 579013ea880dfae203f36dd2ccb0a1edee380171
      HOST_NAME: thebedechkacase.local
      DATABASE_NAME: the-bedechka-case
      DATABASE_URL: mysql://root:root@db:3306/the-bedechka-case
      MAILER_URL: null://localhost
